package com.application.app.miniApps.UserMiniApp;

public enum UserCommand {
	GET_USER_OBJECTS_BY_TYPE,
	GET_USER_OBJECTS_BY_ALIAS_PATTERN,
	GET_USER_OBJECTS_BY_ALIAS,
	DELETE_USER_OBJECT_BY_ID,
	GET_USER_OBJECTS_BY_PROPERTY,
	GET_OBJECTS_BY_PROPERTY,
	GET_OBJECTS_BY_TYPE_AND_PROPERTY
}
